### ISSUE TITLE
后端返回的数据还是的json格式

### ISSUE THREAD

**Issue by kerwinguo** [yinjihuan/spring-boot-starter-encrypt#12]
后端返回的数据还是的json格式.目前返回的是String类型,前端在response接收到之前 会报一个js的JSON.parse的错误.

补充CryptoJS的引入:
var CryptoJS = require("crypto-js");

**Comment by yinjihuan** [comment]
https://github.com/yinjihuan/spring-boot-starter-encrypt-example  有示例代码
