### ISSUE TITLE
com.cxytiandi.encrypt.util.AesEncryptUtils 这两行代码有必要吗？

### ISSUE THREAD

**Issue by JesseHu1520** [yinjihuan/spring-boot-starter-encrypt#3]
![image](https://user-images.githubusercontent.com/11732424/41595389-2fddc292-73f9-11e8-8315-e8c0e048131b.png)

**Comment by yinjihuan** [comment]
真仔细，这2行确实没用，是另一种写法才会用到的

**Comment by qjyoung** [comment]
针对每一个用户生成一个aes key吗，用不同的aes key加解密可以吗，貌似代码里是写死的？

**Comment by yinjihuan** [comment]
可以啊，这就是我在文章后面提高的，通过协商的方式来获取加密的key,通过这种方式就是每个用户都有不同的key,但这样你就必须把key存储起来，我这边是一个通用性质的框架，肯定是采用配置的方式，你可以自己去扩展
