### ISSUE TITLE
加密返回值发送到了前端，前端js怎么解密？能不能具体说明一下

### ISSUE THREAD

**Issue by seasonszx** [yinjihuan/spring-boot-starter-encrypt#8]
你在主页中说：
js加密文件请参考我GitHub中encrypt中的aes.js,crypto-js.js,pad-zeropadding.js
能否直接发地址？我真的在你github找半天也没找到。
谢谢

**Comment by yinjihuan** [comment]
https://github.com/yinjihuan/spring-boot-starter-encrypt-example
